### ISSUE TITLE
Class 'Aschmelyun\Larametrics\Models\LarametricsLog' not found 

### ISSUE THREAD

**Issue by thiagolcks** [aschmelyun/larametrics#69]
Hi!

Today, out of the blue I started to get this error on the server. In my localhost it was working properly. I tried to:
- Reboot the server to free some RAM
- Run `composer dump-autoload`
- Update the package to 1.2.1 (from 1.2)

I'm using Laravel 7.27.4 and PHP 7.4.8.

I had to disable the package on the server.

Here is the log:
```[2020-10-26 09:09:47] production.ERROR: Uncaught Error: Class 'Aschmelyun\Larametrics\Models\LarametricsLog' not found in /var/www/my-project/releases/523/vendor/aschmelyun/larametrics/src/Actions/SaveLog.php:44
Stack trace:
#0 /var/www/my-project/releases/523/vendor/aschmelyun/larametrics/src/Actions/SaveLog.php(27): Aschmelyun\Larametrics\Actions\SaveLog->checkExpiredLogs()
#1 /var/www/my-project/releases/523/vendor/aschmelyun/larametrics/src/Listeners/LogListener.php(14): Aschmelyun\Larametrics\Actions\SaveLog->dispatch()
#2 [internal function]: Aschmelyun\Larametrics\Listeners\LogListener->handle()
#3 /var/www/my-project/releases/523/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(400): call_user_func_array()
#4 /var/www/my-project/releases/523/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#5 /var/www/my-project/releases/523/vendor/laravel/framework/src/Illuminate/Log/Logger.php(210): Illuminate\Events\Dispatcher->dispatch()
#6 /var/www/my-project/re {"userId":2,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Aschmelyun\\Larametrics\\Models\\LarametricsLog' not found in /var/www/my-project/releases/523/vendor/aschmelyun/larametrics/src/Actions/SaveLog.php:44
Stack trace:
#0 /var/www/my-project/releases/523/vendor/aschmelyun/larametrics/src/Actions/SaveLog.php(27): Aschmelyun\\Larametrics\\Actions\\SaveLog->checkExpiredLogs()
#1 /var/www/my-project/releases/523/vendor/aschmelyun/larametrics/src/Listeners/LogListener.php(14): Aschmelyun\\Larametrics\\Actions\\SaveLog->dispatch()
#2 [internal function]: Aschmelyun\\Larametrics\\Listeners\\LogListener->handle()
#3 /var/www/my-project/releases/523/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(400): call_user_func_array()
#4 /var/www/my-project/releases/523/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#5 /var/www/my-project/releases/523/vendor/laravel/framework/src/Illuminate/Log/Logger.php(210): Illuminate\\Events\\Dispatcher->dispatch()
#6 /var/www/my-project/re at /var/www/my-project/releases/523/vendor/aschmelyun/larametrics/src/Actions/SaveLog.php:44)
[stacktrace]
#0 {main}
"}```

**Comment by xembill** [comment]
same problem

**Comment by EduCavalheiro** [comment]
Guys, can you add any other package? If so, remove larametrics completely from the project (you can use this reference [remove package](https://linuxhint.com/how-to-remove-a-package-from-laravel-using-composer/)) and try to install again. This should work.

**Comment by ghost** [comment]
Use Laravel Debugging bar its better then Larametrics
